# Generated by Django 4.2.2 on 2023-06-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idpingenerate',
            name='share_price',
            field=models.FloatField(verbose_name='Price of Share'),
        ),
    ]
